name: ci

on:
  pull_request:

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14

      - name: Run tests
        run: make test

      -
        name: Run GoReleaser check
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: check
      -
        name: Run GoReleaser snapshot
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: --snapshot --skip-publish --rm-dist
